# Generated by Django 5.2.8 on 2025-11-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(blank=True, db_column='Tipo_Documento', max_length=100, null=True)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=255, null=True)),
                ('url_documento', models.CharField(blank=True, db_column='Url_documento', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.CharField(db_column='CNPJ', max_length=20, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(blank=True, db_column='Razao_social', max_length=255, null=True)),
                ('nome_fantasia', models.CharField(blank=True, db_column='Nome_fantasia', max_length=255, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, db_column='Inscricao_municipal', max_length=50, null=True)),
                ('tipo_empresa', models.CharField(blank=True, db_column='Tipo_Empresa', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=50, null=True)),
                ('logradouro', models.CharField(blank=True, db_column='Logradouro', max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=100, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=20, null=True)),
                ('pais', models.CharField(blank=True, db_column='Pais', max_length=100, null=True)),
                ('data_de_registro', models.DateField(blank=True, db_column='Data_de_registro', null=True)),
            ],
            options={
                'db_table': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_de_usuario', models.CharField(blank=True, db_column='Tipo_de_usuario', max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=20, null=True, unique=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_column='User', max_length=100, null=True)),
                ('senha', models.CharField(blank=True, db_column='Senha', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=50, null=True)),
                ('logradouro', models.CharField(blank=True, db_column='Logradouro', max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=100, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=20, null=True)),
                ('pais', models.CharField(blank=True, db_column='Pais', max_length=100, null=True)),
                ('data_de_registro', models.DateField(blank=True, db_column='Data_de_registro', null=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(db_column='Documento_ID', on_delete=django.db.models.deletion.CASCADE, related_name='empresas_relacionadas', to='core.documento')),
                ('empresa_cnpj', models.ForeignKey(db_column='Empresa_CNPJ', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_empresas', to='core.empresa')),
            ],
            options={
                'db_table': 'Documentos_Empresa',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='empresa_cnpj',
            field=models.ForeignKey(blank=True, db_column='Empresa_CNPJ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.empresa'),
        ),
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('comprovante_pagamento', models.IntegerField(blank=True, db_column='Comprovante_pagamento', null=True)),
                ('tipo_imposto', models.CharField(blank=True, db_column='Tipo_Imposto', max_length=100, null=True)),
                ('competencia', models.CharField(blank=True, db_column='Competencia', max_length=50, null=True)),
                ('jurisdicao', models.CharField(blank=True, db_column='Jurisdicao', max_length=100, null=True)),
                ('data_pagamento', models.DateField(blank=True, db_column='Data_Pagamento', null=True)),
                ('data_vencimento', models.DateField(blank=True, db_column='Data_Vencimento', null=True)),
                ('valor', models.DecimalField(blank=True, db_column='Valor', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('documento', models.ForeignKey(blank=True, db_column='Documento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impostos', to='core.documento')),
                ('empresa_cnpj', models.ForeignKey(db_column='Empresa_CNPJ', on_delete=django.db.models.deletion.CASCADE, related_name='impostos', to='core.empresa')),
            ],
            options={
                'db_table': 'Imposto',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, db_column='Descricao', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('nivel_de_prioridade', models.CharField(blank=True, db_column='Nivel_de_prioridade', max_length=50, null=True)),
                ('criado_em', models.DateField(blank=True, db_column='Criado_em', null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='Usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='core.usuario')),
            ],
            options={
                'db_table': 'Tarefa',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('assunto', models.CharField(blank=True, db_column='Assunto', max_length=255, null=True)),
                ('mensagem', models.TextField(blank=True, db_column='Mensagem', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('criado_em', models.DateField(blank=True, db_column='Criado_em', null=True)),
                ('usuario', models.ForeignKey(db_column='Usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.usuario')),
            ],
            options={
                'db_table': 'Notificacao',
            },
        ),
        migrations.CreateModel(
            name='EmpresasUsuarioCliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(blank=True, db_column='Tipo_usuario', max_length=50, null=True)),
                ('empresa_cnpj', models.ForeignKey(db_column='Empresa_CNPJ', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_clientes', to='core.empresa')),
                ('usuario_cliente', models.ForeignKey(db_column='Usuario_Cliente_CPF', on_delete=django.db.models.deletion.CASCADE, related_name='empresas_como_cliente', to='core.usuario', to_field='cpf')),
            ],
            options={
                'db_table': 'Empresas_Usuario_Cliente',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='submetido_por',
            field=models.ForeignKey(blank=True, db_column='Submetido_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_submetidos', to='core.usuario'),
        ),
    ]
