# Generated by Django 5.2.8 on 2025-11-24 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='empresa_cnpj',
            field=models.ForeignKey(blank=True, db_column='Empresa_CNPJ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, db_column='Prazo', null=True),
        ),
    ]
